version: '3'

services:
  ##
  # Database container
  #
  mariadb:
    image: mariadb:10.3.4
    env_file: cocos.env
    volumes:
      - mariadb:/var/lib/mysql/
    restart: always

  ##
  # Web server container
  #
  nginx:
    image: nginx:1.13
    volumes:
      - ${PWD}/nginx/:/etc/nginx/
      - certs:/etc/letsencrypt/
      - certs-data:/data/letsencrypt/
      - cocos:/data/cocos/
      - pressbook:/data/pressbook/
      - moodle:/data/moodle/
      - moodle-data:/data/moodle-data/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    links:
      - php
    restart: always

  ##
  # PHP FPM container
  #
  php:
    build: php
    volumes:
      - cocos:/data/cocos/
      - pressbook:/data/pressbook/
      - moodle:/data/moodle/
      - moodle-data:/data/moodle-data/

volumes:
  # CoCOS data volume
  cocos:

  # Pressbook data volume
  pressbook:

  # CoCOON data volume
  cocoon:

  # Moodle data volumes
  moodle:
  moodle-data:

  # Database volume
  mariadb:

  # Certificate data volumes
  certs:
  certs-data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.8.1/24
